### ISSUE TITLE
The interface opens successfully, but when I start Live, the face appears black. Why is this happening, and how can I fix it?

### ISSUE THREAD

**Issue by hhhaiai** [hacksider/Deep-Live-Cam#210]
The interface opens successfully, but when I start Live, the face appears black. Why is this happening, and how can I fix it?
<img width="584" alt="image" src="https://github.com/user-attachments/assets/b3e64693-825d-4215-a250-20b7c77fd6bc">

<img width="581" alt="image" src="https://github.com/user-attachments/assets/627d6cef-5bb2-4849-b358-f05392887688">

**Comment by hhhaiai** [comment]
image not real people. from net web

**Comment by hhhaiai** [comment]
when run 
```
$python run.py
Frame processor face_enhancer not found
2024-08-12 17:45:17.621 Python[58252:278202] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
```

**Comment by hhhaiai** [comment]
MacBook Pro
1. 2.4 GHz 八核Intel Core i9
2. 
AMD Radeon Pro 5500M 8 GB
Intel UHD Graphics 630 1536 MB
3. 64 GB 2667 MHz DDR4
4. os version:  14.4.1

**Comment by William-island** [comment]
Try strictly follow the official tutorial:
pip uninstall onnxruntime onnxruntime-gpu
pip install onnxruntime-gpu==1.16.3

**Comment by AlexUrrutia** [comment]
@William-island 
```
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.16.3 (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu==1.16.3
```

**Comment by sunyq1995** [comment]
I meet same error but I use windows11 and without GPU, Error:
[ WARN:1@763.558] global cap_msmf.cpp:471 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -1072873821
[ WARN:1@763.568] global cap_msmf.cpp:483 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072873821
[ WARN:1@764.451] global cap_msmf.cpp:471 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -1072873821
[ WARN:1@764.470] global cap_msmf.cpp:483 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072873821
[ WARN:2@825.359] global cap_msmf.cpp:471 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -1072873821
[ WARN:2@825.363] global cap_msmf.cpp:483 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072873821

**Comment by hhhaiai** [comment]
@William-island   failed 
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.16.3 (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu==1.16.3

**Comment by ANK789** [comment]
win10 ，without GPU， running result is the same as the subject, with a large black face

**Comment by William-island** [comment]
I can find the package from tsinghua index.
![image](https://github.com/user-attachments/assets/c7f326d2-dd50-47a5-8786-8a98bd38f27b)

**Comment by aamasimak** [comment]
for people that struggle with onnx 1.16.3, make sure your python is 3.10, if it is it will be installed automatically
it worked but on an env using py 3.10

**Comment by sunyq1995** [comment]
> or people that struggle with onnx 1.16.3, make sure your python is 3.10, if it is it will be installed automatically
> it worked on an env using py 3.10

it works, really thanks!

**Comment by maximka1980** [comment]
if i install onnxruntime-gpu==1.16.3 programm dont start with errors 

(deep) PS D:\deep_live_cam\Deep-Live-Cam> python .\run.py
Traceback (most recent call last):
  File "D:\deep_live_cam\Deep-Live-Cam\run.py", line 3, in <module>
    from modules import core
  File "D:\deep_live_cam\Deep-Live-Cam\modules\core.py", line 20, in <module>
    import modules.ui as ui
  File "D:\deep_live_cam\Deep-Live-Cam\modules\ui.py", line 10, in <module>
    from modules.face_analyser import get_one_face
  File "D:\deep_live_cam\Deep-Live-Cam\modules\face_analyser.py", line 2, in <module>
    import insightface
  File "D:\deep_live_cam\Deep-Live-Cam\deep\Lib\site-packages\insightface\__init__.py", line 16, in <module>
    from . import model_zoo
  File "D:\deep_live_cam\Deep-Live-Cam\deep\Lib\site-packages\insightface\model_zoo\__init__.py", line 1, in <module>
    from .model_zoo import get_model
  File "D:\deep_live_cam\Deep-Live-Cam\deep\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 22, in <module>
    class PickableInferenceSession(onnxruntime.InferenceSession):
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'onnxruntime' has no attribute 'InferenceSession'
(deep) PS D:\deep_live_cam\Deep-Live-Cam>

but if i installed onnxruntime-gpu==1.19 program starts properly  but face is like black square

pyenv global 3.10 local 3.10 


how to fix i?

**Comment by aamasimak** [comment]
> if i install onnxruntime-gpu==1.16.3 programm dont start with errors
> 
> (deep) PS D:\deep_live_cam\Deep-Live-Cam> python .\run.py Traceback (most recent call last): File "D:\deep_live_cam\Deep-Live-Cam\run.py", line 3, in from modules import core File "D:\deep_live_cam\Deep-Live-Cam\modules\core.py", line 20, in import modules.ui as ui File "D:\deep_live_cam\Deep-Live-Cam\modules\ui.py", line 10, in from modules.face_analyser import get_one_face File "D:\deep_live_cam\Deep-Live-Cam\modules\face_analyser.py", line 2, in import insightface File "D:\deep_live_cam\Deep-Live-Cam\deep\Lib\site-packages\insightface__init__.py", line 16, in from . import model_zoo File "D:\deep_live_cam\Deep-Live-Cam\deep\Lib\site-packages\insightface\model_zoo__init__.py", line 1, in from .model_zoo import get_model File "D:\deep_live_cam\Deep-Live-Cam\deep\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 22, in class PickableInferenceSession(onnxruntime.InferenceSession): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: module 'onnxruntime' has no attribute 'InferenceSession' (deep) PS D:\deep_live_cam\Deep-Live-Cam>
> 
> but if i installed onnxruntime-gpu==1.19 program starts properly but face is like black square
> 
> pyenv global 3.10 local 3.10
> 
> how to fix i?

@maximka1980 from what I noticed you are running this using only `python .\run.py` from documentation u should use `python run.py --execution-provider cuda` if u are using cuda and keep the same onnxruntime-gpu==1.16.3

`pip uninstall onnxruntime onnxruntime-gpu
pip install onnxruntime-gpu==1.16.3`

**Comment by maximka1980** [comment]
@aamasimak i am use cuda, i  am starting bat file with cuda provider. "pip uninstall onnxruntime onnxruntime-gpu pip install onnxruntime-gpu==1.16.3" dont work properly because pip install onnxruntime-gpu==1.16.3 dont working yet.

**Comment by hhhaiai** [comment]
has no cuda (navid) , can work?

**Comment by aamasimak** [comment]
> @aamasimak i am use cuda, i am starting bat file with cuda provider. "pip uninstall onnxruntime onnxruntime-gpu pip install onnxruntime-gpu==1.16.3" dont work properly because pip install onnxruntime-gpu==1.16.3 dont working yet.

@maximka1980 what do u mean doesnt work? If u are unable to download it probably u dont have the right python version 3.10

Also will be better to share ur output so we know what is going on

**Comment by aamasimak** [comment]
> has no cuda (navid) , can work?

@hhhaiai i believe it can run on cpu, check documentation

**Comment by exploretech** [comment]
> if i install onnxruntime-gpu==1.16.3 programm dont start with errors
> 
> (deep) PS D:\deep_live_cam\Deep-Live-Cam> python .\run.py Traceback (most recent call last): File "D:\deep_live_cam\Deep-Live-Cam\run.py", line 3, in from modules import core File "D:\deep_live_cam\Deep-Live-Cam\modules\core.py", line 20, in import modules.ui as ui File "D:\deep_live_cam\Deep-Live-Cam\modules\ui.py", line 10, in from modules.face_analyser import get_one_face File "D:\deep_live_cam\Deep-Live-Cam\modules\face_analyser.py", line 2, in import insightface File "D:\deep_live_cam\Deep-Live-Cam\deep\Lib\site-packages\insightface__init__.py", line 16, in from . import model_zoo File "D:\deep_live_cam\Deep-Live-Cam\deep\Lib\site-packages\insightface\model_zoo__init__.py", line 1, in from .model_zoo import get_model File "D:\deep_live_cam\Deep-Live-Cam\deep\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 22, in class PickableInferenceSession(onnxruntime.InferenceSession): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: module 'onnxruntime' has no attribute 'InferenceSession' (deep) PS D:\deep_live_cam\Deep-Live-Cam>
> 
> but if i installed onnxruntime-gpu==1.19 program starts properly but face is like black square
> 
> pyenv global 3.10 local 3.10
> 
> how to fix i?

first of all install this `pip install insightface==0.7.3`

**Comment by hhhaiai** [comment]
> pip install insightface==0.7.3

It can work in windows, mac (intel) can't work.

```
Frame processor face_enhancer not found
```

**Comment by hhhaiai** [comment]
> for people that struggle with onnx 1.16.3, make sure your python is 3.10, if it is it will be installed automatically it worked on an env using py 3.10

$pip install onnx==1.16.3
ERROR: Could not find a version that satisfies the requirement onnx==1.16.3 (from versions: 0.1, 0.2, 0.2.1, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.1.2, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.8.1, 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.13.0, 1.13.1, 1.14.0, 1.14.1, 1.15.0, 1.16.0, 1.16.1, 1.16.2)
ERROR: No matching distribution found for onnx==1.16.3

**Comment by hhhaiai** [comment]
> pip install insightface==0.7.3

same case
