### ISSUE TITLE
Start-up problem

### ISSUE THREAD

**Issue by akirayamaoka32** [hacksider/Deep-Live-Cam#622]
It happens after I select a photo and click Live. 

C:\Users\rocs\Deep-Live-Cam>python run.py
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\rocs/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\rocs/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\rocs/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\rocs/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\rocs/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\rocs\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\rocs\AppData\Local\Programs\Python\Python310\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\rocs\Deep-Live-Cam\modules\ui.py", line 141, in <lambda>
    live_button = ctk.CTkButton(root, text='Live', cursor='hand2', command=lambda: webcam_preview(root))
  File "C:\Users\rocs\Deep-Live-Cam\modules\ui.py", line 458, in webcam_preview
    create_webcam_preview()
  File "C:\Users\rocs\Deep-Live-Cam\modules\ui.py", line 498, in create_webcam_preview
    temp_frame = frame_processor.process_frame(source_image, temp_frame)
  File "C:\Users\rocs\Deep-Live-Cam\modules\processors\frame\face_swapper.py", line 65, in process_frame
    temp_frame = swap_face(source_face, target_face, temp_frame)
  File "C:\Users\rocs\Deep-Live-Cam\modules\processors\frame\face_swapper.py", line 49, in swap_face
    return get_face_swapper().get(temp_frame, target_face, source_face, paste_back=True)
  File "C:\Users\rocs\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\model_zoo\inswapper.py", line 50, in get
    latent = source_face.normed_embedding.reshape((1,-1))
AttributeError: 'NoneType' object has no attribute 'normed_embedding'
![image](https://github.com/user-attachments/assets/1b1856a7-2148-47c9-8745-4c248db38b0c)

**Comment by akirayamaoka32** [comment]
2 files in the models folder I added, python version 3.10 because it doesn't work on 3.12.

**Comment by Updatedme** [comment]
I can personally assist you if that's fine for you, here's my whatsapp 
https://wa.me/message/GXQYWX4XRTXGB1 +2347081306010
