### ISSUE TITLE
The app starts transparent!

### ISSUE THREAD

**Issue by donnadulcinea** [hacksider/Deep-Live-Cam#597]
Seems like everything was ok with the install.

When I run I get the error: / warning:

```
> python run.py --execution-provider cuda
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\dulci\.pyenv\pyenv-win\versions\3.10.6\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\dulci\.pyenv\pyenv-win\versions\3.10.6\lib\tkinter\__init__.py", line 839, in callit
    func(*args)
  File "C:\Users\dulci\Documents\Development\Deep-Live-Cam\.venv\lib\site-packages\customtkinter\windows\widgets\scaling\scaling_tracker.py", line 
186, in check_dpi_scaling
    window.block_update_dimensions_event()
  File "C:\Users\dulci\.pyenv\pyenv-win\versions\3.10.6\lib\tkinter\__init__.py", line 2383, in __getattr__
    return getattr(self.tk, attr)
AttributeError: '_tkinter.tkapp' object has no attribute 'block_update_dimensions_event'
(.venv) PS C:\Users\dulci\Documents\Development\Deep-Live-Cam>
``` 

And the application starts so transparent (opacity super low) that I can barely see it and I can't use it, because it is almost invisible against the desktop background.

Can anybody suggest how to fix it?

I am working with venv python 3.10.6.

**Comment by bkosowski** [comment]
I have the exact same issue when running `run-cuda.bat`.
System: Windows 11, NVIDIA, Python 3.11.

**Comment by kur00kami123** [comment]
Am having the same issue too... Please some one who know.... Help us... Be our saviour T_T

**Comment by hacksider** [comment]
Can you share the screenshot?

**Comment by hacksider** [comment]
can you pip install these requirements?
tkinterdnd2==0.4.2
customtkinter==5.2.2

**Comment by kur00kami123** [comment]
Says error could not find a version that satisfies the requirement tkinterdnd==0.4.2

**Comment by kur00kami123** [comment]
![IMG-20240918-WA0063](https://github.com/user-attachments/assets/bfdafac5-f5d9-4a0d-abfd-5cf24eec44f5)

**Comment by hacksider** [comment]
pip install tkinterdnd2

**Comment by hacksider** [comment]
pip install customtkinter==5.2.2

**Comment by bkosowski** [comment]
This doesn't do anything, before the requirements are already there. `pip list` shows me:
```
customtkinter               5.2.2
tkinterdnd2                  0.4.2
```

And I have the same problem with nearly invisible window.

**Comment by hacksider** [comment]
can you pull again to see if this fixes the issue?

**Comment by hacksider** [comment]
can you check again now?

**Comment by Adhambec** [comment]
yes problem

**Comment by bkosowski** [comment]
> can you check again now?

That's a peculiar question, since you reverted changes to a README file.

If you're asking, does it mean that it works for you on the latest main branch at the moment (3e1f333e5e05345a1f5b3481126931f0484b2858)?

**Comment by kur00kami123** [comment]
Hello... If i run the code... Same error but the deepfacelive is transparant and working.... But all face swaps live or img... Have black box in them

**Comment by Flansi** [comment]
Got the same issue:

python run.py --execution-provider cuda --execution-threads 60 --max-memory 60
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\hanne\anaconda3\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\hanne\anaconda3\lib\tkinter\__init__.py", line 839, in callit
    func(*args)
  File "G:\App\Deep-Live-Cam\env\lib\site-packages\customtkinter\windows\widgets\scaling\scaling_tracker.py", line 186, in check_dpi_scaling
    window.block_update_dimensions_event()
  File "C:\Users\hanne\anaconda3\lib\tkinter\__init__.py", line 2383, in __getattr__
    return getattr(self.tk, attr)
AttributeError: '_tkinter.tkapp' object has no attribute 'block_update_dimensions_event'

**Comment by bkosowski** [comment]
@Flansi And what is your system? Operating system, Python version? I reckon you have an NVIDIA GPU.

**Comment by hacksider** [comment]
I still dont get why you have transparent UI's even after all the last UI changes are reverted 😕

**Comment by kur00kami123** [comment]
Python version is 3.10.11...ffmpeg installed... But still.... That error comes out and the ui is like 5% visible
AttributeError: '_tkinter.tkapp' object has no attribute 'block_update_dimensions_event'

**Comment by Flansi** [comment]
> @Flansi And what is your system? Operating system, Python version? I reckon you have an NVIDIA GPU.

Upsi, Win 11, RTX4090, python 3.10.9

**Comment by hacksider** [comment]
> dimensions

When was your last pull? I made some changes 12 hours ago.

**Comment by Flansi** [comment]
> > dimensions
> 
> When was your last pull? I made some changes 12 hours ago.

Just pulled, still transparent.

python run.py --execution-provider cuda --execution-threads 60 --max-memory 60
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\hanne\anaconda3\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\hanne\anaconda3\lib\tkinter\__init__.py", line 839, in callit
    func(*args)
  File "G:\App\Deep-Live-Cam\env\lib\site-packages\customtkinter\windows\widgets\scaling\scaling_tracker.py", line 186, in check_dpi_scaling
    window.block_update_dimensions_event()
  File "C:\Users\hanne\anaconda3\lib\tkinter\__init__.py", line 2383, in __getattr__
    return getattr(self.tk, attr)
AttributeError: '_tkinter.tkapp' object has no attribute 'block_update_dimensions_event'

**Comment by nguyensi22** [comment]
I also encountered the same phenomenon when opening the app but it still didn't work because 'tkinterdnd2' was missing.

**Comment by hacksider** [comment]
Kindly get the latest pull

**Comment by Flansi** [comment]
Now it starts a few ms without the transparency and then it gets transparent again.
As it gets transparent the error message is shown

![transparent](https://github.com/user-attachments/assets/dd23a3f7-d261-4308-99e7-1a892c1078a5)

python run.py --execution-provider cuda --execution-threads 60 --max-memory 60
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\hanne\anaconda3\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\hanne\anaconda3\lib\tkinter\__init__.py", line 839, in callit
    func(*args)
  File "G:\App\Deep-Live-Cam\env\lib\site-packages\customtkinter\windows\widgets\scaling\scaling_tracker.py", line 186, in check_dpi_scaling
    window.block_update_dimensions_event()
  File "C:\Users\hanne\anaconda3\lib\tkinter\__init__.py", line 2383, in __getattr__
    return getattr(self.tk, attr)
AttributeError: '_tkinter.tkapp' object has no attribute 'block_update_dimensions_event'

**Comment by kur00kami123** [comment]
Same error out here too
AttributeError: '_tkinter.tkapp' object has no attribute 'block_update_dimensions_event'
... T_T comon great minds of the world.... Help T_T

**Comment by bkosowski** [comment]
@hacksider Yesterday you reverted some irrelevant changes to the README file. But today you reverted breaking changes to the UI code. And I confirm that the revert fixed the issue.

The UI looks good now.

**Comment by kur00kami123** [comment]
@bkosowski... Your Ui is visible? If so how did u do it... Also u dont get  the  error
AttributeError: '_tkinter.tkapp' object has no attribute 'block_update_dimensions_event'
Anymore?

**Comment by bkosowski** [comment]
@kur00kami123 Yes, today's version is working fine. I suggest deleting the folder and cloning the repository anew. (You may want to save your models though).

**Comment by hacksider** [comment]
Closing this as the fix is confirmed

**Comment by hacksider** [comment]
@KRSHH

**Comment by KRSHH** [comment]
Hi @donnadulcinea , although I wasn't able to reproduce your issue, I have made a few changes to the code, and have tested it (It worked properly). Please test it out by cloning my fork and tell us if you face any issues.

**Comment by donnadulcinea** [comment]
> Hi @donnadulcinea , although I wasn't able to reproduce your issue, I have made a few changes to the code, and have tested it (It worked properly). Please test it out by cloning my fork and tell us if you face any issues.

Thank you! The last fixes are working. Then I had other problems with the models (https://github.com/hacksider/Deep-Live-Cam/issues/613) but I fixed them with a new shared model.

**Comment by KRSHH** [comment]
> > Hi @donnadulcinea , although I wasn't able to reproduce your issue, I have made a few changes to the code, and have tested it (It worked properly). Please test it out by cloning my fork and tell us if you face any issues.
> 
> Thank you! The last fixes are working. Then I had other problems with the models (#613) but I fixed them with a new shared model.

So, is my [fork](https://github.com/KRSHH/Deep-Live-Cam) working without issues?

**Comment by donnadulcinea** [comment]
> > > Hi @donnadulcinea , although I wasn't able to reproduce your issue, I have made a few changes to the code, and have tested it (It worked properly). Please test it out by cloning my fork and tell us if you face any issues.
> > 
> > 
> > Thank you! The last fixes are working. Then I had other problems with the models (#613) but I fixed them with a new shared model.
> 
> So, is my [fork](https://github.com/KRSHH/Deep-Live-Cam) working without issues? @donnadulcinea

Yes, I cloned everything and the fork is working as well. I had previously fixed the issue with the commit `cad40b25dc23d13c533d2696b987af922f10e225`.

Thanks again @KRSHH .

**Comment by KRSHH** [comment]
@hacksider I guess you can remerge the updated version now...

**Comment by hacksider** [comment]
Will do :) thanks @KRSHH

**Comment by hacksider** [comment]
@KRSHH kindly send me an email (email is in my profile)

**Comment by KRSHH** [comment]
> @KRSHH kindly send me an email (email is in my profile)
Done
